// BlueprintGeneratedClass AIRangedAttackFunctions.AIRangedAttackFunctions_C
// Size: 0x28 (Inherited: 0x28)
struct UAIRangedAttackFunctions_C : UBlueprintFunctionLibrary {

	void GetVFXDataFromWeaponTransportRowHandle(struct FDataTableRowHandle inWeaponTransportHandle, struct UObject* __WorldContext, struct FYFXCategoryRow OutFXCategory, bool bSuccessfull); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.GetVFXDataFromWeaponTransportRowHandle // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void PlayMuzzleFXFromRangedAttackDefinitionNew(struct FDataTableRowHandle InWeaponTransportRowHandle, struct AActor* InAICharacterOwner, struct UObject* __WorldContext); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.PlayMuzzleFXFromRangedAttackDefinitionNew // (Static|Private|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void Fire Projectile Now from Ranged Attack Definition(struct AYAICharacter* AIAttacker, struct AActor* Victim, struct FYAIRangedAttackDefinitionNew AIRangedAttackDefinition, struct AYProjectile* PreSpawnedActor, struct UObject* __WorldContext); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.Fire Projectile Now from Ranged Attack Definition // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void DetermineAttackLocation(struct AActor* ActorVictim, struct UObject* __WorldContext, struct FVector AttackLocation); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.DetermineAttackLocation // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void DetermineVelocityLaunchFromRangedAttackDefinition(struct AYAICharacter* Shooter, struct FVector ShootFromLocation, struct FVector shootAtLocation, struct FYAIRangedAttackDefinitionNew AIRangedAttackDefinition, struct UObject* __WorldContext, struct FVector LaunchVelocity, float GravityZMultiplier); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.DetermineVelocityLaunchFromRangedAttackDefinition // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void DetermineVelocityLaunch(struct AYAICharacter* Shooter, struct FVector ShootFromLocation, struct FVector shootAtLocation, int32_t AIAttackIndex, struct UObject* __WorldContext, struct FVector LaunchVelocity, float GravityZMultiplier); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.DetermineVelocityLaunch // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void DetermineTimeItTakesForProjectileToLocationFromRangedAttackDefinition(struct AYAICharacter* Shooter, struct FVector ShootFromLocation, struct FVector shootAtLocation, struct FYAIRangedAttackDefinitionNew AIAttackIndex, struct UObject* __WorldContext, float Time); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.DetermineTimeItTakesForProjectileToLocationFromRangedAttackDefinition // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void DetermineTimeItTakesForProjectileToLocation(struct AYAICharacter* Shooter, struct FVector ShootFromLocation, struct FVector shootAtLocation, int32_t AIAttackIndex, struct UObject* __WorldContext, float Time); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.DetermineTimeItTakesForProjectileToLocation // (Static|Private|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void ApplyWeaponSpread(struct FVector Direction, struct AYAICharacter* Attacker, struct UObject* __WorldContext, struct FVector DirectionAdjusted); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.ApplyWeaponSpread // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void TryAdjustShootAtLocationByTraceDown(struct FVector shootAtLocation, bool ShootAtGround, struct UObject* WorldContextObj, struct UObject* __WorldContext, struct FVector ShootAtLocationAdjusted); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.TryAdjustShootAtLocationByTraceDown // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void Predicated Target LocationFromRangedAttackDefinition(struct AYAICharacter* AIAttacker, struct AActor* Victim, struct FVector ShootFromLocation, struct FVector shootAtLocation, float Accuracy, struct FYAIRangedAttackDefinitionNew AIRangedAttackDefinition, struct UObject* __WorldContext, struct FVector ShootAtLocationPredicted); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.Predicated Target LocationFromRangedAttackDefinition // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void Predicated Target Location(struct AYAICharacter* AIAttacker, struct AActor* Victim, struct FVector ShootFromLocation, struct FVector shootAtLocation, float Accuracy, struct UObject* __WorldContext, struct FVector ShootAtLocationPredicted); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.Predicated Target Location // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void FireProjectileNow(struct AYAICharacter* AIAttacker, struct AActor* Victim, int32_t RangedAttackIndex, struct UObject* __WorldContext); // Function AIRangedAttackFunctions.AIRangedAttackFunctions_C.FireProjectileNow // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
};

