// BlueprintGeneratedClass MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C
// Size: 0x28 (Inherited: 0x28)
struct UMatchPhaseFunctionLibrary_BP_C : UBlueprintFunctionLibrary {

	void GetCurrentMatchPhaseVisualRow(struct UObject* WorldContextObject, struct UObject* __WorldContext, struct FYMatchPhaseVisualRow VIsualRow, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetCurrentMatchPhaseVisualRow // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void GetVisualRowFromDefinitionRowHandle(struct FDataTableRowHandle DefinitionRowHandle, struct UObject* __WorldContext, struct FYMatchPhaseVisualRow VIsualRow, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetVisualRowFromDefinitionRowHandle // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void GetVisualRowFromDefinitionRow(struct FYMatchPhaseDefinitionRow DefinitionRow, struct UObject* __WorldContext, struct FYMatchPhaseVisualRow VIsualRow, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetVisualRowFromDefinitionRow // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void GetVisualRowHandleFromDefinitionRowHandle(struct FDataTableRowHandle DefinitionRowHandle, struct UObject* __WorldContext, struct FDataTableRowHandle VisualRowHandle, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetVisualRowHandleFromDefinitionRowHandle // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void GetCurrentMatchPhaseGameplayData(struct UObject* WorldContextObject, struct UObject* __WorldContext, struct FYMatchPhaseGameplayRow GameplayRow, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetCurrentMatchPhaseGameplayData // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1e02480
	void GetGameplayRowFromDefinitionRow(struct FYMatchPhaseDefinitionRow DefintionRow, struct UObject* __WorldContext, struct FYMatchPhaseGameplayRow GameplayRow, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetGameplayRowFromDefinitionRow // (Static|Private|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void GetGameplayRowFromDefinitionRowHandle(struct FDataTableRowHandle DefinitionRowHandle, struct UObject* __WorldContext, struct FYMatchPhaseGameplayRow GameplayRow, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetGameplayRowFromDefinitionRowHandle // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void GetDefinitionRowFromDefinitionRowHandle(struct FDataTableRowHandle DefinitionRowHandle, struct UObject* __WorldContext, struct FYMatchPhaseDefinitionRow DefinitionRow, bool Result); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetDefinitionRowFromDefinitionRowHandle // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void GetMatchPhaseDirectorComponent(struct UObject* WorldContextObject, struct UObject* __WorldContext, struct UMatchPhaseDirectorComponent_BP_C* MatchPhaseDirector); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.GetMatchPhaseDirectorComponent // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
	void IsUsingNewMatchPhaseFlow(struct UObject* WorldContextObject, struct UObject* __WorldContext, bool IsUsingNewMatchPhaseFlow); // Function MatchPhaseFunctionLibrary_BP.MatchPhaseFunctionLibrary_BP_C.IsUsingNewMatchPhaseFlow // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1e02480
};

